#!/bin/sh
export PATH=/mnt/secure/bin:/sbin:/usr/sbin:$PATH
chmod 755 /mnt/secure
sleep 2
# safety escape
kc=$(dmesg | grep gpio_keys_gpio_isr | wc -l)
if [ $kc -gt 10 ]; then
	exit
fi
export PATH=/mnt/secure/bin:/sbin:/usr/sbin:$PATH
. /mnt/ext1/system/config/rootsettings.cfg
for f in /mnt/ext1/system/init.d/*.sh /mnt/secure/etc/init.d/*.sh; do
        n=${f##*/}
        bn=${n:3}
        id=${bn/.sh/}
        if [ -f "$f" ] && [ "$(eval echo \${$id})" != "0" ]; then
        	$f $bn
	fi
done
