#!/bin/sh
sleep 2
# safety escape
kc=$(dmesg | grep gpio_keys_gpio_isr | wc -l)
if [ $kc -gt 10 ]; then
	exit
fi
export PATH=/mnt/secure/bin:/sbin:/usr/sbin:$PATH
. /mnt/ext1/system/config/rootsettings.cfg
for n in /mnt/ext1/system/init.d/*.sh /mnt/secure/init.d/*.sh; do
        n=${n##*/}
        bn=${n:3}
        id=${bn/.sh/}
	if [ -f "$n" ] && [ "$(echo $id)" != "0" ]; then
        	$n
	fi
done
